version: '3.8'

services:

    database:
      container_name: postgres
      image: 'postgres:latest'
      restart: always
      ports:
        - 5332:5432

      environment:
        POSTGRES_DB: posts
        DATABASE_HOST: 127.0.0.1
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin
        PGDATA: /data/postgres

      volumes:
        - "database:/data/postgres"
      networks:
        - database

